In [1]:
import pandas as pd
from pathlib import Path
import fitz

In [2]:
DATA_DIR = Path("../data/raw")
pdf_files = list(DATA_DIR.rglob("*.pdf"))
print(f"Total PDFs found: {len(pdf_files)}")
for pdf in pdf_files:
    print(pdf)

Total PDFs found: 5
..\data\raw\alphabet(google)\Alphabet_2025_Annual_Report.pdf
..\data\raw\amazon\Amazon_2025_Annual_Report.pdf
..\data\raw\apple\Apple_2025_Annual_Report.pdf
..\data\raw\microsoft\Microsoft_2025_Annual_Report.pdf
..\data\raw\nvidia\NVIDIA_2025_Annual_Report.pdf

In [3]:
data = []
for pdf in pdf_files:
    data.append({
        "Company": pdf.parent.name,
        "File Name": pdf.name,
        "Full Path": str(pdf),
        "File Size (MB)": round(pdf.stat().st_size / (1024 * 1024), 2)
    })
df = pd.DataFrame(data)
df

,Company,File Name,Full Path,File Size (MB)
0,alphabet(google),Alphabet_2025_Annual_Report.pdf,..\data\raw\alphabet(google)\Alphabet_2025_Ann...,29.60
1,amazon,Amazon_2025_Annual_Report.pdf,..\data\raw\amazon\Amazon_2025_Annual_Report.pdf,1.56
2,apple,Apple_2025_Annual_Report.pdf,..\data\raw\apple\Apple_2025_Annual_Report.pdf,1.77
3,microsoft,Microsoft_2025_Annual_Report.pdf,..\data\raw\microsoft\Microsoft_2025_Annual_Re...,2.01
4,nvidia,NVIDIA_2025_Annual_Report.pdf,..\data\raw\nvidia\NVIDIA_2025_Annual_Report.pdf,47.66

In [7]:
df.sort_values(
    by="File Size (MB)",
    ascending=False
)

,Company,File Name,Full Path,File Size (MB)
4,nvidia,NVIDIA_2025_Annual_Report.pdf,..\data\raw\nvidia\NVIDIA_2025_Annual_Report.pdf,47.66
0,alphabet(google),Alphabet_2025_Annual_Report.pdf,..\data\raw\alphabet(google)\Alphabet_2025_Ann...,29.60
3,microsoft,Microsoft_2025_Annual_Report.pdf,..\data\raw\microsoft\Microsoft_2025_Annual_Re...,2.01
2,apple,Apple_2025_Annual_Report.pdf,..\data\raw\apple\Apple_2025_Annual_Report.pdf,1.77
1,amazon,Amazon_2025_Annual_Report.pdf,..\data\raw\amazon\Amazon_2025_Annual_Report.pdf,1.56

In [4]:
df = df[
    [
        "Company",
        "File Name",
        "File Size (MB)",
        "Full Path"
    ]
]

df

,Company,File Name,File Size (MB),Full Path
0,alphabet(google),Alphabet_2025_Annual_Report.pdf,29.60,..\data\raw\alphabet(google)\Alphabet_2025_Ann...
1,amazon,Amazon_2025_Annual_Report.pdf,1.56,..\data\raw\amazon\Amazon_2025_Annual_Report.pdf
2,apple,Apple_2025_Annual_Report.pdf,1.77,..\data\raw\apple\Apple_2025_Annual_Report.pdf
3,microsoft,Microsoft_2025_Annual_Report.pdf,2.01,..\data\raw\microsoft\Microsoft_2025_Annual_Re...
4,nvidia,NVIDIA_2025_Annual_Report.pdf,47.66,..\data\raw\nvidia\NVIDIA_2025_Annual_Report.pdf

In [12]:
pdf_path = pdf_files[0]
doc = fitz.open(pdf_path)
print(doc)
print("Total Pages :", len(doc))
print(doc.metadata)

Document('..\data\raw\alphabet(google)\Alphabet_2025_Annual_Report.pdf')
Total Pages : 112
{'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'creator': 'Adobe InDesign 18.5 (Macintosh)', 'producer': 'Adobe PDF Library 17.0', 'creationDate': "D:20260417210816+05'30'", 'modDate': "D:20260420191957-04'00'", 'trapped': '', 'encryption': None}

In [5]:
document_info = []
for pdf in pdf_files:
    doc = fitz.open(pdf)
    document_info.append({
        "Company": pdf.parent.name,
        "Pages": len(doc),
        "PDF Format": doc.metadata.get("format"),
        "Encrypted": doc.metadata.get("encryption"),
        "Creator": doc.metadata.get("creator")
    })
    doc.close()
document_df = pd.DataFrame(document_info)
document_df

,Company,Pages,PDF Format,Encrypted,Creator
0,alphabet(google),112,PDF 1.7,None,Adobe InDesign 18.5 (Macintosh)
1,amazon,92,PDF 1.3,None,Adobe InDesign 15.0 (Macintosh)
2,apple,80,PDF 1.4,None,Workiva
3,microsoft,80,PDF 1.7,None,Microsoft® Word 2019
4,nvidia,181,PDF 1.6,None,Adobe Acrobat (64-bit) 25.1.20474

In [14]:
# Open the first document
doc = fitz.open(pdf_files[0])

# Read the first page
page = doc.load_page(4)

# Extract text
text = page.get_text()

print(repr(text[:1000]))

print(doc)
doc.close()

'UNITED STATES\nSECURITIES AND EXCHANGE COMMISSION\nWashington, D.C. 20549\nFORM 10-K \n\xa0ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934\nFor the fiscal year ended December 31, 2025\nOR\n\xa0TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934\nFor the transition period from __________ to __________.\nCommission file number: 001-37580 \nDelaware\n(State or other jurisdiction of \nincorporation or organization)\nALPHABET INC.\n(Exact name of registrant as specified in its charter)\n61-1767919\n(I.R.S. Employer \nIdentification No.)\n1600 Amphitheatre Parkway\nMountain View, CA 94043\n(Address of principal executive offices, including zip code)\n (650) 253-0000\n(Registrant’s telephone number, including area code)\nSECURITIES REGISTERED PURSUANT TO SECTION 12(B) OF THE ACT:\nTitle of each class\nTrading Symbol(s)\nName of each exchange on which registered\nClass A Common Stock, $0.001 par value\nGOOGL\nNasdaq Stock Market LLC\n(Nasdaq Global Select '
Document('..\data\raw\alphabet(google)\Alphabet_2025_Annual_Report.pdf')

In [7]:
# counting number of characters each pag of a file has
page_stats = []
doc = fitz.open(pdf_files[0])
for page_num in range(len(doc)):
    page = doc.load_page(page_num)
    text = page.get_text()
    page_stats.append({
        "Page": page_num + 1,
        "Characters": len(text),
        "Words": len(text.split())
    })
doc.close()
page_df = pd.DataFrame(page_stats)
page_df.head(10)

   Page  Characters  Words
0     1           3      1
1     2           0      0
2     3        3076    481
3     4        3103    508
4     5        3117    497
5     6        3073    480
6     7        1468    218
7     8        2956    420
8     9        4126    628
9    10        4422    678

In [8]:
print("Total Pages :", len(page_df))
print("Total Characters :", page_df["Characters"].sum())
print("Total Words :", page_df["Words"].sum())
print("\nAverage Characters/Page :", round(page_df["Characters"].mean(),2))
print("Average Words/Page :", round(page_df["Words"].mean(),2))
print("\nMaximum Characters on a Page :", page_df["Characters"].max())
print("Minimum Characters on a Page :", page_df["Characters"].min())

Total Pages : 112
Total Characters : 357639
Total Words : 54145

Average Characters/Page : 3193.21
Average Words/Page : 483.44

Maximum Characters on a Page : 6046
Minimum Characters on a Page : 0

In [10]:
empty_pages = page_df[page_df["Words"] == 0]
empty_pages

   Page  Characters  Words
1     2           0      0

In [11]:
doc = fitz.open(pdf_files[0])
total_images = 0

for page in doc:
    images = page.get_images()

    total_images += len(images)

print("Total Images :", total_images)

doc.close()

Total Images : 3